/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 6f639a0d55fd835d9554b3ca9363545a)
interface __BaseEnv_Env {
	CF_VERSION_METADATA: WorkerVersionMetadata;
	ASSETS: Fetcher;
	PUBLIC_GO_API_URL: "https://api.scoracle.com/api/v1";
	SCORACLE_API_TIMEOUT_MS: "12000";
	SCORACLE_INTERNAL_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_GO_API_URL" | "SCORACLE_API_TIMEOUT_MS" | "SCORACLE_INTERNAL_KEY">> {}
}
