import "./legal.css";

export default function Terms() {
  return (
    <main class="legal-main">
      <h1>Terms of Service</h1>
      <p class="legal-effective">Last Updated: May 2, 2026</p>

      <p>
        Welcome to Scoracle. These Terms of Service ("Terms") govern your access to and use of the
        websites, applications, APIs, and services (collectively, the "Service") operated by
        Scoracle LLC, a Michigan limited liability company ("Scoracle," "we," "us," or "our"),
        including without limitation scoracle.com and its subdomains (such as ai.scoracle.com,
        sandbox.scoracle.com, fantasy.scoracle.com, and stats.scoracle.com).
      </p>
      <p>
        By accessing or using the Service, you agree to be bound by these Terms. If you do not
        agree, do not access or use the Service.
      </p>

      <h2>1. About the Service</h2>
      <p>
        Scoracle provides sports analytics, statistical models, predictive insights, and related
        tools and content. The Service is provided for informational, educational, and
        entertainment purposes only.
      </p>
      <p>
        <strong>
          Scoracle is not a sportsbook, gambling platform, fantasy sports operator, or financial
          advisor.
        </strong>{" "}
        Predictions, projections, ratings, rankings, and other outputs generated by the Service are
        statistical estimates only. They are not guarantees, recommendations to wager, or advice of
        any kind. You are solely responsible for any decisions you make based on information from
        the Service.
      </p>

      <h2>2. Eligibility</h2>
      <p>
        You must be at least 18 years old (or the age of majority in your jurisdiction, whichever
        is greater) to use the Service. By using the Service, you represent and warrant that you
        meet this requirement and that you have the legal capacity to enter into these Terms.
      </p>

      <h2>3. Accounts</h2>
      <p>Some features of the Service may require you to create an account. You agree to:</p>
      <ul>
        <li>Provide accurate, current, and complete information during registration;</li>
        <li>Maintain the security and confidentiality of your account credentials;</li>
        <li>Promptly notify us of any unauthorized access to your account; and</li>
        <li>Accept responsibility for all activities that occur under your account.</li>
      </ul>
      <p>
        We reserve the right to suspend or terminate any account at our sole discretion, including
        for violation of these Terms.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose or in violation of any applicable law or regulation;</li>
        <li>Scrape, crawl, harvest, or otherwise extract data from the Service through automated means without our prior written consent;</li>
        <li>Reverse engineer, decompile, or attempt to derive the source code, models, schemas, or algorithms underlying the Service, except to the extent such restriction is prohibited by applicable law;</li>
        <li>Resell, sublicense, or redistribute Service content, data, or outputs without authorization;</li>
        <li>Use the Service to develop a competing product or service;</li>
        <li>Interfere with or disrupt the integrity, performance, or security of the Service;</li>
        <li>Circumvent any rate limits, access controls, or authentication mechanisms;</li>
        <li>Upload or transmit malicious code, viruses, or any other harmful material; or</li>
        <li>Use the Service in any manner that could damage, disable, overburden, or impair our infrastructure.</li>
      </ul>

      <h2>5. Intellectual Property</h2>

      <h3>5.1 Our Rights</h3>
      <p>
        The Service, including all software, models, derived statistics, schemas, ratings,
        projections, visualizations, design elements, text, graphics, logos, and other content
        (excluding User Content and Third-Party Content as defined below), is owned by Scoracle
        LLC or its licensors and is protected by copyright, trademark, trade secret, and other
        intellectual property laws.
      </p>
      <p>
        <strong>All Rights Reserved.</strong> Except for the limited license granted to you in
        Section 5.2, no rights or licenses are granted to you, by implication or otherwise, under
        any of our intellectual property.
      </p>
      <p>The "Scoracle" name and logo are trademarks of Scoracle LLC.</p>

      <h3>5.2 Limited License</h3>
      <p>
        Subject to your compliance with these Terms, we grant you a limited, non-exclusive,
        non-transferable, revocable license to access and use the Service for your personal,
        non-commercial use.
      </p>

      <h3>5.3 Raw Statistical Facts</h3>
      <p>
        You acknowledge that raw box score statistics and other purely factual data points are not
        subject to copyright under United States law. Our intellectual property claims extend to
        our original selection, arrangement, derivation, presentation, schemas, and analytical
        outputs — not to the underlying public facts themselves.
      </p>

      <h3>5.4 User Content</h3>
      <p>
        If you submit any content to the Service (e.g., feedback, comments, suggestions), you grant
        us a worldwide, royalty-free, perpetual, irrevocable, sublicensable license to use,
        reproduce, modify, and display such content in connection with operating and improving the
        Service. You represent that you have the rights necessary to grant this license.
      </p>

      <h2>6. Third-Party Content and Data</h2>

      <h3>6.1 Sports League Names and Marks</h3>
      <p>
        The Service may reference league names, team names, player names, and related marks
        (including those of the NBA, NFL, MLB, NHL, NCAA, and other organizations). Scoracle is
        not affiliated with, endorsed by, or sponsored by any sports league, team, or athlete. All
        such names and marks are the property of their respective owners and are used by Scoracle
        for nominative, identification, and informational purposes only.
      </p>

      <h3>6.2 Third-Party Data Providers</h3>
      <p>
        The Service incorporates data from third-party providers under license. You agree not to
        use the Service in any manner that would violate the terms of those underlying licenses.
        We make no representations regarding the accuracy, completeness, or timeliness of
        third-party data.
      </p>

      <h3>6.3 Third-Party Links</h3>
      <p>
        The Service may contain links to third-party websites or services. We are not responsible
        for the content, policies, or practices of any third party.
      </p>

      <h2>7. APIs</h2>
      <p>
        If you access any Scoracle API, your use is additionally subject to any API-specific
        documentation, rate limits, and authentication requirements we publish. We may change,
        deprecate, or discontinue any API at any time without notice.
      </p>

      <h2>8. Fees and Payment</h2>
      <p>
        Some features of the Service may require payment. If you purchase a paid subscription or
        product:
      </p>
      <ul>
        <li>Fees are described at the point of purchase and are charged in U.S. dollars unless otherwise noted;</li>
        <li>Subscriptions automatically renew unless cancelled before the renewal date;</li>
        <li>All fees are non-refundable except where required by law; and</li>
        <li>We may change pricing with reasonable notice.</li>
      </ul>

      <h2>9. Disclaimers</h2>
      <p>
        THE SERVICE IS PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTIES OF ANY
        KIND, EXPRESS OR IMPLIED. TO THE MAXIMUM EXTENT PERMITTED BY LAW, SCORACLE DISCLAIMS ALL
        WARRANTIES, INCLUDING WITHOUT LIMITATION IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS
        FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF
        DEALING OR USAGE OF TRADE.
      </p>
      <p>WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT:</p>
      <ul>
        <li>THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR SECURE;</li>
        <li>ANY PREDICTIONS, PROJECTIONS, OR ANALYTICS WILL BE ACCURATE OR REALIZED;</li>
        <li>DEFECTS WILL BE CORRECTED; OR</li>
        <li>THE SERVICE OR THE SERVERS THAT MAKE IT AVAILABLE ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS.</li>
      </ul>
      <p>
        YOU ASSUME ALL RISK ARISING FROM YOUR USE OF THE SERVICE AND FROM ANY DECISIONS YOU MAKE
        BASED ON INFORMATION OBTAINED FROM THE SERVICE.
      </p>

      <h2>10. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT WILL SCORACLE LLC, ITS AFFILIATES, OR
        ITS LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY,
        OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFITS, REVENUE, DATA, GOODWILL, OR BUSINESS
        OPPORTUNITIES, ARISING OUT OF OR RELATING TO THESE TERMS OR YOUR USE OF THE SERVICE,
        REGARDLESS OF THE THEORY OF LIABILITY AND EVEN IF WE HAVE BEEN ADVISED OF THE POSSIBILITY
        OF SUCH DAMAGES.
      </p>
      <p>
        OUR TOTAL CUMULATIVE LIABILITY ARISING OUT OF OR RELATING TO THESE TERMS OR THE SERVICE
        WILL NOT EXCEED THE GREATER OF (A) THE AMOUNT YOU PAID TO SCORACLE IN THE TWELVE (12)
        MONTHS PRECEDING THE EVENT GIVING RISE TO THE CLAIM, OR (B) ONE HUNDRED U.S. DOLLARS
        ($100.00).
      </p>
      <p>
        Some jurisdictions do not allow the exclusion or limitation of certain damages, so the
        above limitations may not apply to you in full.
      </p>

      <h2>11. Indemnification</h2>
      <p>
        You agree to indemnify, defend, and hold harmless Scoracle LLC and its officers, members,
        employees, and agents from any claims, damages, liabilities, losses, and expenses
        (including reasonable attorneys' fees) arising out of or relating to:
      </p>
      <ul>
        <li>Your use or misuse of the Service;</li>
        <li>Your violation of these Terms;</li>
        <li>Your violation of any law or the rights of any third party; or</li>
        <li>Any content you submit to the Service.</li>
      </ul>

      <h2>12. Termination</h2>
      <p>
        We may suspend or terminate your access to the Service at any time, with or without cause
        and with or without notice. Upon termination, your right to use the Service will
        immediately cease. Sections 5, 6, 9, 10, 11, 13, and 14 will survive termination.
      </p>

      <h2>13. Governing Law and Dispute Resolution</h2>
      <p>
        These Terms are governed by the laws of the State of Michigan, without regard to its
        conflict-of-laws principles. You agree that any dispute arising out of or relating to
        these Terms or the Service will be resolved exclusively in the state or federal courts
        located in Oakland County, Michigan, and you consent to the personal jurisdiction of such
        courts.
      </p>

      <h2>14. Changes to These Terms</h2>
      <p>
        We may revise these Terms from time to time. The most current version will always be
        posted at this URL with an updated "Last Updated" date. Material changes will be
        communicated through the Service or by other reasonable means. Your continued use of the
        Service after such changes constitutes your acceptance of the revised Terms.
      </p>

      <h2>15. Miscellaneous</h2>
      <ul>
        <li>
          <strong>Entire Agreement.</strong> These Terms, together with any policies referenced
          herein (including our Privacy Policy), constitute the entire agreement between you and
          Scoracle regarding the Service.
        </li>
        <li>
          <strong>Severability.</strong> If any provision of these Terms is held unenforceable,
          the remaining provisions will remain in full force and effect.
        </li>
        <li>
          <strong>No Waiver.</strong> Our failure to enforce any provision will not constitute a
          waiver of that provision.
        </li>
        <li>
          <strong>Assignment.</strong> You may not assign these Terms without our prior written
          consent. We may assign these Terms freely.
        </li>
        <li>
          <strong>No Third-Party Beneficiaries.</strong> These Terms do not create any third-party
          beneficiary rights.
        </li>
      </ul>

      <h2>16. Contact</h2>
      <p>Questions about these Terms? Contact us at:</p>
      <p>
        <strong>Scoracle LLC</strong>
        <br />
        Royal Oak, Michigan
        <br />
        Email: <a href="mailto:legal@scoracle.com">legal@scoracle.com</a>
      </p>

      <p style="margin-top: 2rem">
        See also: <a href="/privacy">Privacy Policy</a>.
      </p>
    </main>
  );
}
